# Generated by Django 5.1.6 on 2025-02-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0002_drug_effective_dose_alter_drug_generic_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='generic_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Generic Code'),
        ),
    ]
