# Generated by Django 5.1.6 on 2025-02-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viper', '0001_initial'),
        ('dr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PatientMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Viper.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dr.patient')),
            ],
        ),
    ]
